pdf:

	pandoc philippe.md -o USECASE_Philippe_administrateur.pdf --number-section
	pandoc jeanmarc.md -o USECASE_Jean-Marc_client.pdf --number-section
	pandoc Marcelle_Jacques.md -o USECASE_Marcelle_et_Jacques_clients.pdf --number-section
