pdf:
	pandoc sql.md --toc -o sql.pdf

	pandoc sql.md -o sql.tex

	pandoc philippe.md -o philippe.tex

	pandoc jeanmarc.md -o jeanmarc.tex

	pandoc Marcelle_Jacques.md -o Marcelle_Jacques.tex

    # pandoc Projet_IHM.md -o Projet_IHM_BCRY.pdf --toc --template=templates/template_etude.latex --number-section

	pandoc Projet_IHM.md -o Projet_IHM_BCRY.pdf --toc --template=templates/template_etude.latex --number-section
