pdf:
	# pandoc sql.md --toc -o sql.pdf

    # pandoc Projet_IHM.md -o Projet_IHM_BCRY.pdf --toc --template=templates/template_etude.latex --number-section

	pandoc Projet_IHM.md -o Projet_IHM_BCRY.pdf --toc --template=templates/template_etude.latex --number-section
